version: '3'

services:

  app:
    build:
      context: .docker/node
      dockerfile: Dockerfile.dev
    container_name: app
    entrypoint: dockerize -wait tcp://db:5432 -timeout 20s docker-entrypoint.sh
    volumes:
      - .:/usr/src/app
    networks:
      - rentx-network
    tty: true
    #ports:
     # - 3000:3000
      #- 9229:9229
    links:
      - db
    depends_on:
      - db

  db:
    image: postgres:alpine3.14
    container_name: db
    restart: always
    ports:
      - 5432:5432
    tty: true
    environment:
      POSTGRES_USER: "docker"
      POSTGRES_PASSWORD: "docker"
      POSTGRES_DB: "rentx"
    volumes:
      - .docker/postgres/pgdata:/var/lib/postgresql/data
    networks:
      - rentx-network

networks:
  rentx-network:
    driver: bridge



